Carla_Town10:
  filepath: configs/c10_perception.yaml
  hdmap_sampling_resolution: 0.1
  perception_model_max_agents: 12
  perception_model_prediction_grid_size: 100
  state_default_heading: 0
async:
  detection_strategy: ''
  filepath: configs/c10_perception.yaml
  hdmap_sampling_resolution: 0.1
  perception_model_max_agents: 12
  perception_model_prediction_grid_size: 100
  prediction_strategy: ''
  state_default_heading: 0
  tracking_strategy: ''
default:
  detection_strategy: ''
  filepath: configs/c10_perception.yaml
  hdmap_sampling_resolution: 0.1
  perception_model_max_agents: 12
  perception_model_prediction_grid_size: 100
  prediction_horizon: 2.0
  prediction_strategy: ''
  state_default_heading: 0
  tracking_strategy: ''
perception exp:
  detection_strategy: ''
  filepath: configs/c10_perception.yaml
  hdmap_sampling_resolution: 0.1
  perception_model_max_agents: 12
  perception_model_prediction_grid_size: 100
  prediction_strategy: ''
  state_default_heading: 0
  tracking_strategy: ''
ros:
  filepath: configs/c10_perception.yaml
  hdmap_sampling_resolution: 0.1
  perception_model_max_agents: 12
  perception_model_prediction_grid_size: 100
  state_default_heading: 0
sync:
  detection_strategy: ''
  filepath: configs/c10_perception.yaml
  hdmap_sampling_resolution: 0.1
  perception_model_max_agents: 12
  perception_model_prediction_grid_size: 100
  prediction_strategy: ''
  state_default_heading: 0
  tracking_strategy: ''
