B: {}
Carla_Town10: {}
SAN: {}
default:
  p50_bg_color: '#333333'
  p50_dark_mode: true
  p50_fg_color: white
  p50_hide_menubar: false
  p50_shortcut_mode: false
  p55_frenet_view_follow_planner: false
  p55_frenet_zoom: 30.0
  p55_global_plan_velocity_scale: relative
  p55_global_plan_view: true
  p55_global_view_follow_planner: false
  p55_global_zoom: 30.0
  p55_local_plan_view: true
  p55_show_global_plan: true
  p55_show_global_plan_boundaries: true
  p55_show_legend: false
  p55_show_lidar_clusters: true
  p55_show_local_frenet_view: true
  p55_show_local_global_view: false
  p55_show_local_lattice: true
  p55_show_local_plan: true
  p55_show_occupancy_flow: false
  p55_show_past_locations: true
  p55_show_perception_extras: false
  p55_show_race_boundary: true
  p55_show_state: true
  p55_xy_zoom: 30.0
  p57_disable_log: false
  p57_log_font: Courier
  p57_log_font_size: 11
  p57_log_pull_time: 50
  p57_log_view_default_height: 12
  p57_log_view_expanded: false
  p57_log_view_expended_height: 35
  p57_max_log_lines: 1000
  p57_show_common_logs: true
  p57_show_control_logs: true
  p57_show_core_logs: true
  p57_show_execute_logs: true
  p57_show_perceive_logs: true
  p57_show_plan_logs: true
  p57_show_plugins_logs: true
  p57_show_vis_logs: true
  p59_mouse_drag_slowdown_factor: 0.5
global planning: {}
hdmap: {}
joystick: {}
local planning: {}
perception:
  p50_bg_color: '#333333'
  p50_dark_mode: true
  p50_fg_color: white
  p50_hide_menubar: false
  p50_shortcut_mode: false
  p55_frenet_view_follow_planner: false
  p55_frenet_zoom: 30.0
  p55_global_plan_velocity_scale: relative
  p55_global_plan_view: false
  p55_global_view_follow_planner: false
  p55_global_zoom: 30.0
  p55_local_plan_view: true
  p55_show_global_plan: true
  p55_show_global_plan_boundaries: true
  p55_show_legend: false
  p55_show_lidar_clusters: true
  p55_show_lidar_frenet: false
  p55_show_lidar_global: true
  p55_show_local_frenet_view: true
  p55_show_local_global_view: false
  p55_show_local_lattice: true
  p55_show_local_plan: true
  p55_show_occupancy_flow: false
  p55_show_past_locations: true
  p55_show_perception_extras: false
  p55_show_race_boundary: true
  p55_show_state: true
  p55_xy_zoom: 30.0
  p57_disable_log: false
  p57_log_font: Courier
  p57_log_font_size: 11
  p57_log_pull_time: 50
  p57_log_view_default_height: 12
  p57_log_view_expanded: false
  p57_log_view_expended_height: 35
  p57_max_log_lines: 1000
  p57_show_common_logs: true
  p57_show_control_logs: true
  p57_show_core_logs: true
  p57_show_execute_logs: true
  p57_show_perceive_logs: true
  p57_show_plan_logs: true
  p57_show_plugins_logs: true
  p57_show_vis_logs: true
  p59_mouse_drag_slowdown_factor: 0.5
robot: {}
ros: {}
